name: Agentic RAG CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      qdrant:
        image: qdrant/qdrant:latest
        ports:
          - 6333:6333
        # it ensures that the Qdrant service is fully initialized and ready to accept requests before the test steps run
        options: >-
          --health-cmd "apt-get update && apt-get install -y curl && curl -f http://localhost:6333/readyz || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx pytest-asyncio
    - name: Create Dummy Qdrant Collection
      run: |
        # Thoda wait karein taaki DB ready ho jaye
        sleep 5 
        curl -X PUT "http://localhost:6333/collections/agentic_rag_db" \
          -H "Content-Type: application/json" \
          -d '{ "vectors": { "size": 768, "distance": "Cosine" } }'

    - name: Run Unit Tests
      env:
        CI: "true"
        PYTHONPATH: .
        groq_api_key: "dummy_key" 
        hf_api_key: "dummy_key"
        
        HUGGINGFACEHUB_API_TOKEN: "dummy_key"
        TAVILY_API_KEY: "dummy_key"
        
        # 3. Database
        QDRANT_URL: "http://localhost:6333"
        QDRANT_API_KEY: "dummy_key"
      run: |
        pytest

   # JOB 2: 
  build-and-push-image:
    needs: build-and-test 
    runs-on: ubuntu-latest
    # ye ensure krta h push confirm ho aur pull request open ni ho tabhi docker image banana h
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .                  # Root folder context (taaki app.py dikhe)
          file: docker/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/production-rag:latest